Class {
	#name : #GameyeV5InputDataUtils,
	#superclass : #AbstractGameyeInputDataUtils,
	#category : #'Gameye-Core'
}

{ #category : #accessing }
GameyeV5InputDataUtils class >> gameyeVersion [ 

	^ GameyeVersion v5
]

{ #category : #accessing }
GameyeV5InputDataUtils class >> numberOfExportedSpreadsheetColumns [

	^ 22
]

{ #category : #'see class side' }
GameyeV5InputDataUtils >> seeClassSide [
]
