Class {
	#name : 'GameyeVersion',
	#superclass : 'Object',
	#category : 'Gameye-Model',
	#package : 'Gameye',
	#tag : 'Model'
}

{ #category : 'versions' }
GameyeVersion class >> unknown [

	^'unknown'
]

{ #category : 'versions' }
GameyeVersion class >> v4 [

	^'v4'
]

{ #category : 'versions' }
GameyeVersion class >> v5 [

	^'v5'
]

{ #category : 'versions' }
GameyeVersion class >> v5dot05 [

	^'v5.05'
]

{ #category : 'see class side' }
GameyeVersion >> seeClassSide [ 
]
